import { Inter } from "next/font/google";
import { Karla } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import SessionWrapper from "./components/SessionWrapper";
import ToastWrapper from "./components/ToastWrapper.js";
import { StrictMode } from "react";

const inter = Karla({ subsets: ["latin"], fontWeight: "400 700", style: "normal" });

export const metadata = {
  title: "E-shopify - One Stop Tech Shop",
  description: "Generated by create next app",
  icons: {
    icon: "/dhyey.jpg"
  }
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <head>
        <link rel="icon" href="/dhyey.jpg" />
      </head>
      <StrictMode>
      <SessionWrapper>
        <body className={inter.className}>
          <Navbar />
          <main>{children}</main>
          <Footer />
          <ToastWrapper />
        </body>
      </SessionWrapper>
      </StrictMode>

    </html>
  );
}
